## Создание новой фигуры формул

>1. Создаем фигуру "Прямоугольник" произвольного размера (Главная > Инструменты > Прямоугольник).

>2. Открываем таблицу данных фигуры (Нажатие правой кнопкой мыши по фигуре > Данные > Данные фигуры).

>3. Определяем данные фигуры (Нажатие правой кнопкой мыши по таблице данных фигуры > Определить данные фигуры).

>>3.1. В появившейся вкладке появляется возможность добавить одну строку данных. 

>>3.2. Выбираем подпись и имя исходя из необходимого типа данных. Подпись делается на русском языке, а имя исключительно на английском.

>>3.3. Выбираем формат данных (область значений), необходимое значение и сообщение необходимое при пояснении данных.

>>3.4. Нажимаем кнопку "Создать" и создаем необходимое количество данных.

## Добавление свойств фигуры формулы

>1. Открываем таблицу свойств фигуры (Нажатие правой кнопокой мыши по фигуре > Показать таблицу свойств фигуры).
>2. В открытой таблице внаходим следующие столбцы:

>>Shape data - Имя данных

>>Label - Подпись данных

>>Prompt - Сообщение необходимое при пояснении данных

>>Type - Тип данных (значение зависит от типа данных, который мы выбрали в таблице данных фигуры)

>>Format - Формат данных (Область значений)

>>Value - значение данных

>3. Формат данных (область значений) вводится последовательно через ";"

>4. При вводе значения данных имеется возможность вставить формулу расчета путем прописывания имен данных и математических действий между ними

