project:
  type: website

website:
  title: "ГраФиС-блог"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Obsidian-pb/GraFiS-Tactic
format:
  html:
    theme: sandstone
    css: styles.css

lang: ru

